name: "Sync Defaults with Copier"
description: "Install Python and Copier"

inputs:
  python-version:
    description: "The version of Python to use"
    required: true
  copier-template-src:
    description: "Indicate where to get the template from. This can be a git URL or a local path."
    required: true
  copier-destination-path:
    description: "Where to generate the new subproject. It must not exist or be empty."
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v3
      with:
        cache: "pip"
        python-version:  ${{ inputs.python-version }}

    # - id: install-copier
    #   name: Install Copier
    #   run: |
    #       python -m pip install --upgrade --no-cache-dir pip
    #       python -m pip install --no-cache-dir copier
    #   shell: bash

    - id: copier-update
      name: Update Defaults with Copier
      run: pipx run copier --force copy ${{ inputs.copier-template-src }} ${{ inputs.copier-destination-path }}
      shell: bash
