name: "Sync Defaults with Copier"
description: "Install Python and Copier"

inputs:
  python-version:
    description: “The version of Python to use”
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ inputs.python-version }}

    - id: install-copier
      name: Install Copier
      run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir copier
      shell: bash

    - id: copier-update
      name: Update Defaults with Copier
      run: copier --force copy gh:jefftriplett/defaults .
      shell: bash
