name: "Sync Defaults with Copier"
description: "Install Python and Copier"

inputs:
  python-version:
    description: “The version of Python to use”
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version:  ${{ inputs.python-version }}

    - id: copier-update
      name: Update Defaults with Copier
      run: pipx run copier --vcs-ref=HEAD --force update
      shell: bash
